### ISSUE TITLE
Class not found 'org/nd4j/linalg/factory/Nd4j'

### ISSUE THREAD

**Issue by kshitij12345** [deeplearning4j/jumpy#17]
I can successfully run the classpath_test.py,
```
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
```

However when I run array_creation.py,

```
Traceback (most recent call last):
  File "array_creation.py", line 8, in <module>
    class TestArrayCreation(unittest.TestCase):
  File "array_creation.py", line 9, in TestArrayCreation
    init()
  File "/home/x/Desktop/Anaconda/build/lib/python2.7/site-packages/jumpy/__init__.py", line 41, in init
    nd4j = autoclass('org.nd4j.linalg.factory.Nd4j')
  File "/home/x/Desktop/Anaconda/build/lib/python2.7/site-packages/jnius/reflect.py", line 158, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass
jnius.JavaException: Class not found 'org/nd4j/linalg/factory/Nd4j'

```
This is what I get.

I have added the JUMPY_CLASS_PATH to the environment and points the target of the maven build.
However one thing worth mentioning is that the built jars names are `dl4j-1.0-SNAPSHOT.jar` and `original-dl4j-1.0-SNAPSHOT.jar`. Nothing with pattern *-bin.jar .

Also I have tried renaming them to `original-dl4j-1.0-bin.jar` and `dl4j-1.0-bin.jar` which didn't work as well.

Also I have tried placing this
```
    global system
    system = autoclass('java.lang.System')
    system.out.println(system.getProperty('org.bytedeco.javacpp.nopointergc'))
    global Integer
    Integer = autoclass('java.lang.Integer')
    global Float
    Float = autoclass('java.lang.Float')
    global Double
    Double = autoclass('java.lang.Double')
```
before the import of nd4j class and these load successfully.

Please help.

Thank You.

**Comment by akshaysharma096** [comment]
Classpath seems to be the wrong @kshitij12345 we might need to fix this.

**Comment by akshaysharma096** [comment]
I am also facing the same issue @kshitij12345

**Comment by kshitij12345** [comment]
Let me know if you or someone figure this out

**Comment by saudet** [comment]
Could you try again with 1.0.0-SNAPSHOT?

**Comment by agibsonccc** [comment]
@kshitij12345 @akshaysharma096 I would just build an uber jar and point JUMPY_CLASS_PATH at that. Our original docs had it, @farizrahman4u ended up moving it since it was a bit verbose but can be found here:  https://github.com/deeplearning4j/jumpy/blob/master/pom.xml Change the version to: 
1.0.0-alpha
and it should be fairly painless.

**Comment by akshaysharma096** [comment]
Added fix in [#18](https://github.com/deeplearning4j/jumpy/pull/18)

**Comment by akshaysharma096** [comment]
@saudet please note.

**Comment by AlexDBlack** [comment]
Closing due to fix being merged here: https://github.com/deeplearning4j/jumpy/pull/18
